name: Deploy docs browser page

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup doc browser
        uses: ./
        with:
          docs-file: "data/aliases.md"
          xml-file: "data/Arkadia.xml"
      - run: ls ../../_actions/actions